image: docker.nsnw.ca/python3:latest

before_script:
  - apt install -y libgraphviz-dev
  - python3 -V
  - which python3
  - pip3 install -r requirements.txt

stages:
  - test

test:
  stage: test
  script: python3 ./manage.py test
