image: docker.nsnw.ca/python3:latest

before_script:
  - apt install -y locales
  - locale-gen en_US.UTF-8
  - python3 -V
  - which python3
  - pip3 install -r requirements.txt

stages:
  - test

test:
  stage: test
  script: python3 ./manage.py test

variables:
  LANG: en_US.UTF-8
  LANGUAGE: en_US:en
