before_script:
  - apt-get update -qq && apt-get install python3
  - python3 -V
  - which python3
  - pip install -r requirements.txt

stages:
  - test

test:
  stage: test
  scripts: ./manage.py test
