image: ubuntu

before_script:
  - apt-get update -qq && apt-get install -y python3 python3-pip
  - python3 -V
  - which python3
  - pip3 install -r requirements.txt

stages:
  - test

test:
  stage: test
  script: python3 ./manage.py test
