# Generated by Django 2.1.3 on 2018-11-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailing',
            name='departed',
            field=models.BooleanField(default=False),
        ),
    ]
