# Generated by Django 2.1.3 on 2018-11-18 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('data', '0003_sailing_day_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='InPortEvent',
            fields=[
                ('locationevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.LocationEvent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('data.locationevent',),
        ),
        migrations.CreateModel(
            name='OfflineEvent',
            fields=[
                ('locationevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.LocationEvent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('data.locationevent',),
        ),
        migrations.CreateModel(
            name='UnderWayEvent',
            fields=[
                ('locationevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.LocationEvent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('data.locationevent',),
        ),
        migrations.AddField(
            model_name='locationevent',
            name='ferry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Ferry'),
        ),
        migrations.AddField(
            model_name='locationevent',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_data.locationevent_set+', to='contenttypes.ContentType'),
        ),
    ]
