# Generated by Django 2.1.3 on 2018-11-18 08:45

import data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20181118_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadingEvent',
            fields=[
                ('locationevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.LocationEvent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('data.locationevent',),
        ),
        migrations.AddField(
            model_name='ferry',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.Destination'),
        ),
        migrations.AddField(
            model_name='ferry',
            name='heading',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ferry',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ferry',
            name='status',
            field=models.CharField(blank=True, choices=[(data.models.FerryStatus('In Port'), 'In Port'), (data.models.FerryStatus('Under Way'), 'Under Way'), (data.models.FerryStatus('Offline'), 'Offline')], max_length=16, null=True),
        ),
    ]
