# Generated by Django 2.1.3 on 2018-11-18 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20181118_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationEvent',
            fields=[
                ('locationevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.LocationEvent')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.Destination')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('data.locationevent',),
        ),
        migrations.AddField(
            model_name='headingevent',
            name='new_value',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='headingevent',
            name='old_value',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
