# Generated by Django 2.1.3 on 2018-11-18 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20181118_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoppedEvent',
            fields=[
                ('locationevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.LocationEvent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('data.locationevent',),
        ),
        migrations.RemoveField(
            model_name='locationevent',
            name='heading',
        ),
    ]
