# Generated by Django 2.1.3 on 2018-11-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20181118_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailing',
            name='sailing_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
