# Generated by Django 2.1.3 on 2018-11-19 06:27

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20181119_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferry',
            name='status',
            field=models.CharField(blank=True, choices=[(data.models.FerryStatus('In Port'), 'In Port'), (data.models.FerryStatus('Under Way'), 'Under Way'), (data.models.FerryStatus('Offline'), 'Offline')], max_length=32, null=True),
        ),
    ]
