# Generated by Django 2.1.3 on 2018-11-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20181119_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='sailing_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
