# Generated by Django 2.1.3 on 2018-11-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_route_sailing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailing',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
