# Generated by Django 2.1.3 on 2018-11-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_sailing_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailing',
            name='late_leaving',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
