# Generated by Django 2.1.3 on 2018-11-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_sailing_late_leaving'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='sailing_time',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='sailing',
            name='late_arriving',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sailing',
            name='scheduled_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
