# Generated by Django 2.1.3 on 2018-12-21 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_cancelledevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullEvent',
            fields=[
                ('sailingevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.SailingEvent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('data.sailingevent',),
        ),
        migrations.AddField(
            model_name='terminal',
            name='parking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
