# Generated by Django 2.1.3 on 2018-12-21 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('data', '0017_auto_20181221_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ParkingEvent',
            fields=[
                ('terminalevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.TerminalEvent')),
                ('old_value', models.IntegerField(blank=True, null=True)),
                ('new_value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('data.terminalevent',),
        ),
        migrations.AddField(
            model_name='terminalevent',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_data.terminalevent_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='terminalevent',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Terminal'),
        ),
    ]
