# Generated by Django 2.1.3 on 2018-12-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20181221_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailing',
            name='car_percent_full',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sailing',
            name='oversize_percent_full',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
