# Generated by Django 2.1.3 on 2018-12-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20181221_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailing',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
