# Generated by Django 2.1.3 on 2018-12-21 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_sailing_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPercentFullEvent',
            fields=[
                ('sailingevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.SailingEvent')),
                ('old_value', models.IntegerField(blank=True, null=True)),
                ('new_value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('data.sailingevent',),
        ),
        migrations.CreateModel(
            name='OversizePercentFullEvent',
            fields=[
                ('sailingevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.SailingEvent')),
                ('old_value', models.IntegerField(blank=True, null=True)),
                ('new_value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('data.sailingevent',),
        ),
    ]
