# Generated by Django 2.1.7 on 2019-03-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20190301_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
