# Generated by Django 2.1.3 on 2018-12-14 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawHTML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('successful', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ConditionsRawHTML',
            fields=[
                ('rawhtml_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collector.RawHTML')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('collector.rawhtml',),
        ),
        migrations.CreateModel(
            name='ConditionsRun',
            fields=[
                ('run_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collector.Run')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('collector.run',),
        ),
        migrations.CreateModel(
            name='DeparturesRawHTML',
            fields=[
                ('rawhtml_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collector.RawHTML')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('collector.rawhtml',),
        ),
        migrations.CreateModel(
            name='DeparturesRun',
            fields=[
                ('run_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collector.Run')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('collector.run',),
        ),
        migrations.CreateModel(
            name='LocationsRawHTML',
            fields=[
                ('rawhtml_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collector.RawHTML')),
                ('url', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('collector.rawhtml',),
        ),
        migrations.CreateModel(
            name='LocationsRun',
            fields=[
                ('run_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collector.Run')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('collector.run',),
        ),
        migrations.AddField(
            model_name='run',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_collector.run_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='rawhtml',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_collector.rawhtml_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='rawhtml',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Run'),
        ),
    ]
