# Generated by Django 2.1.3 on 2018-12-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
